publication_create:
    path:     /publication/create
    defaults: { _controller: AdminBundle:Article:ajout }
    
publication_delete:
    pattern:  /publication/{id}
    defaults: { _controller: AdminBundle:Article:deleteArticle }


