home_evenement:
    resource: "@HomeBundle/Resources/config/routing/evenement.yml"
    prefix:   /evenement

home_homepage:
    path:     /
    defaults: { _controller: HomeBundle:Default:index }

publication_index:
    path:     /publication
    defaults: { _controller: HomeBundle:Default:notes }