HomeBundle\Entity\Evenement:
    type: entity
    table: null
    repositoryClass: HomeBundle\Repository\EvenementRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        message:
            type: text
    lifecycleCallbacks: {  }
